{% extends "base.html" %}

{% block title %}Exit Callbacks in C{% endblock title %}

{% block styles %}
	<link rel="stylesheet" href="{{ url_for('static', filename='css/blog.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='highlight.js/styles/highlight.css') }}">
{% endblock styles %}

{% block deferred_scripts %}
	<script src="{{ url_for('static', filename='highlight.js/highlight_c.pack.js') }}"></script>
	<script src="{{ url_for('static', filename='blog.js') }}"></script>
{% endblock deferred_scripts %}

{% block navbar %}
	{% include '_blog_navbar.html' %}
{% endblock navbar %}

{% block header %}
	<header>
		<h1>Exit Callbacks Using C stdlib</h1>
		<p>Clean up when a program terminates.</p>
	</header>
{% endblock header %}

{% block content %}
	<section>
		<article class="blog-post">
			<h2>Introduction</h2>
			<p>Unexpectedly exiting a C program can leave resources unreleased.
			The system handles this gracefully in some circumstances, not in others.
			This can lead to socket reuse errors, open filed descriptors, etc.</p>

			<p>The standard library provides two built-in exit codes:</p>
			<code>EXIT_SUCCESS</code>

<pre><code>#include &lt;stdlib.h&gt;

int main(void)
{
    // Terminate program and report succees
    exit(EXIT_SUCCESS);

    // Program never reaches here - exits above
    return 0;
}
</code></pre>

			<code>EXIT_FAILURE</code>
<pre><code>#include &lt;stdlib.h&gt;

int main(void)
{
    // Terminate program and report failure
    exit(EXIT_FAILURE);

    // Program never reaches here - exits above
    return 0;
}
</code></pre>

		</article>
	</section>
{% endblock content %}

{% block footer %}
	<footer></footer>
{% endblock footer %}
